export const SEARCH_CITY_START= 'SEARCH_CITY_START';
export const SEARCH_CITY_SUCCESS= 'SEARCH_CITY_SUCCESS';
export const SEARCH_CITY_FAILURE= 'SEARCH_CITY_FAILURE';
export const START_LOADING= 'START_LOADING';